name: ArtifactTrial

on: 
 push:
  branches: master
  
 pull_request:
  branches: master


  
jobs:
  build:
  
    runs-on: Demo1
    
    steps:
    
     - uses: actions/checkout@v3
     
     - uses: actions/upload-artifact@v3
       with:
        name: MyArtifacts
        
    
